# cacheDir: __generated__
schema: "**/*.graphqls"
schemaEntrypoint: "src/server/graphql/schema/schema.graphqls"
documents: "**/*.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-resolvers
  - typescript-react-apollo
TSConfigFile: tsconfig.json