/* 27bd3518a843c2e0fb24a1dffa0d29010b3e00b9
 * This file is automatically generated by graphql-let. */

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export declare type Maybe<T> = T | null;
export declare type Exact<T extends {
    [key: string]: unknown;
}> = {
    [K in keyof T]: T[K];
};
/** All built-in and custom scalars, mapped to their actual values */
export declare type Scalars = {
    ID: string;
    String: string;
    Boolean: boolean;
    Int: number;
    Float: number;
};
export declare type Mutation = {
    __typename?: 'Mutation';
    recording: RecordingMutation;
};
export declare type RecordingMutation = {
    __typename?: 'RecordingMutation';
    create: Recording;
};
export declare type RecordingMutationCreateArgs = {
    input: CreateRecordingInput;
};
export declare type CreateRecordingInput = {
    operationName: Scalars['String'];
    query: Scalars['String'];
    variables: Scalars['String'];
};
export declare type Query = {
    __typename?: 'Query';
    getRecordings: Array<Maybe<Test>>;
};
export declare type Test = {
    __typename?: 'Test';
    replaceThisBullshxt: Scalars['String'];
};
export declare type Recording = {
    __typename?: 'Recording';
    operationName: Scalars['String'];
    query: Scalars['String'];
    variables: Scalars['String'];
};
export declare type GetRecordingsQueryVariables = Exact<{
    [key: string]: never;
}>;
export declare type GetRecordingsQuery = ({
    __typename?: 'Query';
} & {
    getRecordings: Array<Maybe<({
        __typename?: 'Test';
    } & Pick<Test, 'replaceThisBullshxt'>)>>;
});
export declare const GetRecordingsDocument: DocumentNode<GetRecordingsQuery, GetRecordingsQueryVariables>;
