name: can-publish
on: [push]
jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install Lerna
        run: npm i
      - name: Run "publish:dry"
        run: npm run publish:dry
